baseURL = 'https://kalachlegends.com/'
languageCode = 'ru'
defaultContentLanguage = 'en'
theme = 'congo'
summaryLength = 0
timeout=70000


[services]
  [services.googleAnalytics]
    id = 'G-CLF4ENY543'

[languages]
  [languages.en]
    contentDir = 'content/en'
    languageName = 'English'
    weight = 3
  [languages.ru]
    contentDir = 'content/ru'
    languageName = 'Русский'
    weight = 3

[markup.goldmark.renderHooks.image]
enableDefault = true

[markup.goldmark.renderHooks.link]
enableDefault = true

[[module.mounts]]
source = 'assets'
target = 'assets'

[[module.mounts]]
source = 'attachments'
target = 'assets/attachments'
